[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "starling"
version = "0.1.0"

[[bin]]
name = "starling"
path = "src/bin/starling.rs"
doc = false

[dependencies]
futures = "0.1.13"
tokio-core = "0.1.6"
